# Default values for vertica-chart.

# Image details
image:
  repository: vertica/vertica-ce
  tag: latest
  pullPolicy: IfNotPresent

# Database name
databaseName: vdb

# Replicas for Vertica StatefulSet
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 5433

# Persistent Volume Claim
persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# Database initialization script
initScripts:
  enabled: true
  createSchema: |
    CREATE SCHEMA omniq;
  createUser: |
    CREATE USER cognos IDENTIFIED BY 'password';