apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vertica-chart.fullname" . }}-init-scripts
  labels:
    app: {{ include "vertica-chart.name" . }}
data:
  01-create-schema.sql: |
    {{- if .Values.initScripts.enabled }}
    {{- .Values.initScripts.createSchema | nindent 4 }}
    {{- end }}