apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vertica-init
  labels:
    {{- include "vertica.labels" . | nindent 4 }}
data:
  init-schema.sh: |
    #!/bin/bash
    set -e
    
    # Wait for Vertica to be ready
    until vsql -U ${VERTICA_DB_USER} -w ${VERTICA_DB_PASSWORD} -d ${VERTICA_DB_NAME} -c '\q'; do
      echo "Waiting for Vertica to accept connections..."
      sleep 5
    done

    # Create schema
    vsql -U ${VERTICA_DB_USER} -w ${VERTICA_DB_PASSWORD} -d ${VERTICA_DB_NAME} \
      -c "CREATE SCHEMA IF NOT EXISTS {{ .Values.auth.schemaName }};"
    echo "Schema {{ .Values.auth.schemaName }} created successfully"