apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vertica-chart.fullname" . }}-init-scripts
  labels:
    app: {{ include "vertica-chart.name" . }}
data:
  01-create-schema.sql: |
    {{ .Values.initScripts.createSchema }}
  02-create-user.sql: |
    {{ .Values.initScripts.createUser }}