apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertica-chart.name" . }}
  labels:
    app: {{ include "vertica-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5433
      protocol: TCP
      name: vertica
  selector:
    app: {{ include "vertica-chart.name" . }}