apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "vertica.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: vertica
    protocol: TCP
    name: vertica
  selector:
    {{- include "vertica.selectorLabels" . | nindent 4 }}